[alias]
    # Consolidated descriptive aliases
    test = "nextest run --config-file .cargo/nextest.toml"
    coverage = "llvm-cov nextest --config-file .cargo/nextest.toml --html"
    lcov = "llvm-cov nextest --config-file .cargo/nextest.toml --lcov --output-path lcov.info"
    flamegraph = "flamegraph --bench"

    # Short synonyms for convenience (kept for muscle memory)
    t = "nextest run --config-file .cargo/nextest.toml"
    c = "llvm-cov nextest --config-file .cargo/nextest.toml --html"
    l = "llvm-cov nextest --config-file .cargo/nextest.toml --lcov --output-path lcov.info"
    f = "flamegraph --bench"

[future-incompat-report]
    # Report future incompatibilities in dependencies
    frequency = 'always'

[env]
    # Enable full backtrace for debugging
    RUST_BACKTRACE = "full"

[build]
    rustdocflags = ["--default-theme", "trash", "--theme", ".cargo/theme.css"]
